[project]
name = "kates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "biopython>=1.85",
    "httpx>=0.28.1",
    "scikit-learn>=1.7.2",
    "tensorflow>=2.20.0",
    "typer[all]>=0.19.2",
]
